services:
  octopus-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octopus-dashboard
    ports:
      - "3005:3000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3005/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
